# ======================================================================
# PACKAGES
# ======================================================================
- name: register elasticsearch rpm key
  rpm_key:
    key: http://packages.elasticsearch.org/GPG-KEY-elasticsearch

- name: install repo files
  copy:
    src: repo/{{ item }}.repo
    dest: /etc/yum.repos.d/{{ item }}.repo
  with_items:
  - elasticsearch
  - logstash

- name: install rpm packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - java-1.7.0-openjdk
  - elasticsearch-1.7.2
  - logstash
  - unzip
  - wget

# ======================================================================
# KIBANA
# ======================================================================
- name: download kibana
  get_url:
    url: https://download.elastic.co/kibana/kibana/kibana-4.1.2-linux-x64.zip
    dest: /tmp/kibana-4.1.2.zip

- name: unzip kibana
  unarchive:
    copy: no
    src: /tmp/kibana-4.1.2.zip
    dest: /opt
    creates: /opt/kibana-4.1.2-linux-x64

- name: link kibana
  file:
    src: /opt/kibana-4.1.2-linux-x64
    dest: /opt/kibana
    state: link

- name: supervisor configuration
  copy:
    src: supervisor/{{ item }}.ini
    dest: /etc/supervisord.d/{{ item }}.ini
  with_items:
  - elasticsearch
  - logstash
  - kibana

- name: reload supervisor
  shell: supervisorctl {{ item }}
  with_items:
  - reread
  - update

- name: start services
  supervisorctl:
    name: "{{ item }}"
    state: started
  with_items:
  - elasticsearch
  - logstash
  - kibana

- name: install elastichq locally
  shell: '/usr/share/elasticsearch/bin/plugin -install royrusso/elasticsearch-HQ'
  args:
    creates: '/usr/share/elasticsearch/plugins/HQ'
